import os
import io
import base64
import tempfile
from datetime import datetime
from fpdf import FPDF
from rdkit import Chem
from rdkit.Chem import Draw


REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


def _save_molecule_image_to_file(smiles: str) -> str | None:
    """Render a molecule from SMILES as a temporary PNG file and return its path."""
    mol = Chem.MolFromSmiles(smiles)
    if not mol:
        return None
    img = Draw.MolToImage(mol, size=(400, 400))
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    img.save(tmp, format="PNG")
    tmp.close()
    return tmp.name


def generate_pdf_report(
    smiles: str,
    toxicity: str,
    confidence: float,
    top_features: list[str],
    feature_values: list[float],
    feature_names: list[str],
) -> str:
    """
    Generate a professional PDF report for a toxicity prediction and return the filename.

    The PDF includes:
      - Title and timestamp
      - Input SMILES string
      - Prediction result (Toxic / Non-toxic) and confidence score
      - 2D molecule structure image rendered via RDKit
      - SHAP top contributing features
      - Full feature table
    """

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 60, 120)
    pdf.cell(0, 14, "ToxiGuard AI", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Drug Toxicity Prediction Report", new_x="LMARGIN", new_y="NEXT", align="C")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, f"Generated: {timestamp}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    # ── Divider ────────────────────────────────────────────
    pdf.set_draw_color(30, 60, 120)
    pdf.set_line_width(0.6)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Input SMILES ───────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Input SMILES", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Courier", "", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7, smiles)
    pdf.ln(4)

    # ── Prediction Result ──────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Prediction Result", new_x="LMARGIN", new_y="NEXT")

    if toxicity == "Toxic":
        pdf.set_text_color(200, 30, 30)
    else:
        pdf.set_text_color(30, 150, 30)

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, toxicity, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Confidence Score: {confidence:.2%}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Molecule Image ─────────────────────────────────────
    mol_img_path = _save_molecule_image_to_file(smiles)
    if mol_img_path:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Molecule Structure", new_x="LMARGIN", new_y="NEXT")
        pdf.image(mol_img_path, x=55, w=100)
        pdf.ln(4)
        # Clean up temp file
        try:
            os.unlink(mol_img_path)
        except OSError:
            pass

    # ── SHAP Top Features ──────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Top Contributing Features (SHAP)", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    for i, feat in enumerate(top_features, 1):
        pdf.cell(0, 7, f"  {i}. {feat}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Full Feature Table ─────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Extracted Features", new_x="LMARGIN", new_y="NEXT")

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(30, 60, 120)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(95, 8, "Feature", border=1, fill=True, align="C")
    pdf.cell(95, 8, "Value", border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")

    # Table rows
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    for name, val in zip(feature_names, feature_values):
        pdf.cell(95, 7, str(name), border=1, align="C")
        pdf.cell(95, 7, f"{val:.4f}", border=1, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Footer ─────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(0, 6, "This report was auto-generated by ToxiGuard AI. For research purposes only.", new_x="LMARGIN", new_y="NEXT", align="C")

    # Save PDF
    safe_smiles = "".join(c if c.isalnum() else "_" for c in smiles[:30])
    filename = f"toxiguard_report_{safe_smiles}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)

    return filename
